#
# This pipeline needs the following tasks from Tekton Hub
#   - git-clone
#   - flake8
#
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: cd-pipeline
  
spec:
  params:
    -name: build-image

  tasks:
    - name: clone
      taskRef: 
        name: git-clone
      workspaces: 
        - name: source
          workspace: pipeline-workspace
      params:
        - name: url
          value: "https://github.com/DzhonPeppe/devops-capstone-project"
        - name: revision
          value: "main"
      -name: build-image
    - name: init
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: cleanup

    - name: build
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
      - name: IMAGE
        value: "$(params.build-image)"
      runAfter:
        - tests
        - lint
